spring:
  datasource:
    url: jdbc:mysql://localhost/order_mgmt
    username: root
    password: root1234!

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100